services:
  postgres_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:-crm_database}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - crm_net

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save "" --appendonly no
    networks:
      - crm_net

  clamav-scanner:
    image: clamav/clamav:latest
    restart: always
    networks:
      - crm_net

  api-gateway:
    image: krakend:latest
    restart: always
    ports:
      - "${GATEWAY_HOST_PORT:-8080}:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
      - ./gateway/output:/etc/krakend/static:ro
    depends_on:
      - postgres_db
      - redis
      - clamav-scanner
    networks:
      - crm_net

networks:
  crm_net:
    driver: bridge

volumes:
  postgres_data_prod:
